In [1]:
import numpy as np 

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[7]

7

In [5]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [6]:
arr[0:3] = 100 #numpy arrays have broadcasting ability 

In [7]:
arr  # 100 broadcasted to selected index

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [8]:
slice_of_arr = arr[0:2]

In [9]:
slice_of_arr[0:2] = 54

In [10]:
arr # arr also changed when slice changed since np arrays are memory efficient 

array([ 54,  54, 100,   3,   4,   5,   6,   7,   8,   9])

In [12]:
#to avoid such cases and for making copy we use arr.copy() function 
slice_arr = arr.copy()
slice_arr

array([ 54,  54, 100,   3,   4,   5,   6,   7,   8,   9])

In [13]:
slice_arr[0:9] = 78

In [14]:
slice_arr

array([78, 78, 78, 78, 78, 78, 78, 78, 78,  9])

In [15]:
arr #now arr will not change

array([ 54,  54, 100,   3,   4,   5,   6,   7,   8,   9])

In [16]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr_2d[1][2]

6

In [19]:
arr_2d[1,2]

6

In [20]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
#conditional selection 
arr[arr>50] #returns elements greater than 50 

array([ 54,  54, 100])