In [1]:
import numpy as np

In [7]:
my_list = [1,2,3]
array = np.array(my_list)
array

array([1, 2, 3])

In [8]:
type(array)

numpy.ndarray

In [9]:
my_list = [[1,2,3],[3,4,5]]
twod_array = np.array(my_list)
twod_array

array([[1, 2, 3],
       [3, 4, 5]])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,2),dtype='int')

array([[1, 1],
       [1, 1],
       [1, 1]])

In [21]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5,3)

array([[0.9448015 , 0.37814026, 0.32330315],
       [0.71394934, 0.00796939, 0.73665055],
       [0.55953566, 0.17348827, 0.20423152],
       [0.82459914, 0.65606217, 0.15086965],
       [0.83504452, 0.88625093, 0.17052673]])

In [26]:
np.random.randn(5,2)

array([[-0.66616216, -0.81000947],
       [-0.57515956,  0.26176626],
       [-0.20478095,  0.09232058],
       [ 1.4464622 , -0.08446621],
       [ 0.62569487, -0.59841345]])

In [29]:
np.random.randint(1,50,(5,6))

array([[16, 18,  2, 38, 10, 11],
       [42, 13, 24, 16, 33, 26],
       [12,  9, 40, 29, 23, 32],
       [41,  9,  8, 21, 12, 14],
       [46, 48,  7,  2, 33, 30]])

In [39]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr = arr.reshape(5,2)

In [38]:
arr.shape

(5, 2)

In [40]:
arr.max()

9

In [41]:
arr.argmax()

9