In [1]:
import numpy as np 

In [3]:
arr1 = np.random.randint(1,20,(3,3))
arr1

array([[ 4, 19, 10],
       [14,  3, 17],
       [ 7,  1, 10]])

In [4]:
arr2=np.random.randint(1,50,(3,3))
arr2

array([[36, 11, 34],
       [34, 11,  1],
       [24, 33, 36]])

In [5]:
arr1+ arr2

array([[40, 30, 44],
       [48, 14, 18],
       [31, 34, 46]])

In [6]:
arr1 + 100  #scaler operations

array([[104, 119, 110],
       [114, 103, 117],
       [107, 101, 110]])

In [11]:
arr2 = arr2 ** 2

arr2

array([[1296,  121, 1156],
       [1156,  121,    1],
       [ 576, 1089, 1296]], dtype=int32)

In [12]:
np.sqrt(arr2)

array([[36., 11., 34.],
       [34., 11.,  1.],
       [24., 33., 36.]])